[tool.vulture]
min_confidence = 80
exclude = [
    "venv_test/",
    "venv_test_new/",
    "*.pyc",
    "__pycache__/",
    "node_modules/",
    "dist/",
    "coverage/",
    ".pytest_cache/",
    ".git/",
    # Legacy/experimental code that may have unused components  
    "MakerMatrix/lib/",
    # Task implementations that are registered via class discovery
    "MakerMatrix/tasks/",
    # Test utilities and fixtures
    "MakerMatrix/tests/conftest.py"
]

# Configuration for ignoring false positives
# Add paths to files with intentional unused code
ignore_names = [
    # Test fixtures that appear unused but are used by pytest
    "setup_*",
    "clean_*",
    "sample_*",
    "*_fixture",
    # Common test variables
    "client",
    "session",
    # Database engine parameter used in event handlers
    "connection_record",
    # Imports that are re-exported
    "LabelData",
    "PydanticField",
    "EnrichmentProfileModel",
    "DateTime",
    "Boolean",
    "Integer",
    "Text",
    "relationship",
    "Form",
    "OAuth2PasswordRequestForm",
    "GenericPartQuery",
    "UpdateQuantityRequest",
    "Coroutine",
    "user_models",
    "pytest_asyncio",
    "get_all_suppliers_info",
    "TaskSecurityError",
    "AsyncGenerator",
    # Abstract method parameters
    "print_config",
    # Pytest parametrize parameters that may not be directly used in test body
    "expected_error",
    # Pydantic model configuration
    "model_config",
    # Mock test attributes that appear unused
    "side_effect",
    "__aexit__",
    # FastAPI lifespan function
    "lifespan",
    # Task classes used by task system
    "*Task",
    # Exception handlers registered with FastAPI
    "*_handler",
    # Public API functions that may not be called internally
    "serve_*",
    # Test markers
    "pytestmark",
    # Task discovery functions
    "get_task_class",
    "list_available_tasks"
]

# Paths to ignore completely
ignore_decorators = [
    "@pytest.fixture",
    "@app.middleware",
    "@app.on_event"
]