# Router imports
from . import (
    parts_routes,
    part_allocation_routes,
    locations_routes,
    categories_routes,
    project_routes,
    printer_routes,
    preview_routes,
    utility_routes,
    auth_routes,
    user_management_routes,
    api_key_routes,
    ai_routes,
    import_routes,
    task_routes,
    websocket_routes,
    analytics_routes,
    activity_routes,
    supplier_config_routes,
    supplier_routes,
    rate_limit_routes,
    label_template_routes,

)

__all__ = [
    "parts_routes",
    "part_allocation_routes",
    "locations_routes",
    "categories_routes",
    "project_routes",
    "printer_routes",
    "preview_routes",
    "utility_routes",
    "auth_routes",
    "user_management_routes",
    "api_key_routes",
    "ai_routes",
    "import_routes",
    "task_routes",
    "websocket_routes",
    "analytics_routes",
    "activity_routes",
    "supplier_config_routes",
    "supplier_routes",
    "rate_limit_routes",
    "label_template_routes"
]